### ISSUE TITLE
words without results are getting added to the wordlist

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#353]
also doubleclicking on any of those words from wordlist it does generate a pop-up that loads for ever.
see wordlist screenshot
![loading-wordlist](https://user-images.githubusercontent.com/41396793/82233966-c015f100-98fe-11ea-9c8d-8910e9cfd905.JPG)

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/348#issuecomment-630277132_

There seems to have been an inadvertent change which results in words which did not produce results getting added to the wordlist --  in the prior release we excluded some words from the wordlist. They shouldn't be there, and their presence is also exposing a bug in the lookup code -- if you select a word which doesn't produce results from the wordlist an error gets thrown at HtmlSelector:175     ```let languageCode = typeof this.target.getAttribute === 'function' ? this.target.getAttribute('lang') || this.target.getAttribute('xml:lang') : null``` because in this scenario the selector `target` property is null -- in the constructor for the HTML Selector `this.event.end` is 0 for some reason and does not have a `target` property.

**Comment by balmas** [comment]
Note that although the example above is for Syriac, it occurs for any language if you lookup a word that doesn't produce lexical query results.

So 2 fixes are need:

(1) we should restore the behavior that prevented words without lexical query results from being added to the wordlist (I suspect this might be the result of the ill-advised changes in #291 )

(2) if for some reason a word without results does get added to the list, it shouldn't throw an error resulting in an endless loading dialog (We need to catch the scenario of no event target)

**Comment by irina060981** [comment]
>(1) we should restore the behavior that prevented words without lexical query results from being added to the wordlist (I suspect this might be the result of the ill-advised changes in #291 )

we decided to skip this point on the meeting because there could be some value in saving proper nouns that doesn't have lexical results

**Comment by monzug** [comment]
see my comment to #291

**Comment by irina060981** [comment]
(2) point is fixed and merged
will checks comments in #291 next working day

**Comment by irina060981** [comment]
@monzug, as I could see in comments of #291 there was only one unsolved problem - with for-ever loading word without lexical data

it was solved via #389 

all other points was answered
may be besides this

>>some words are repeated like fortuna, primus, based on the part of speech. the 'missing' words are the one with a failed lexical query. This should be ok. do you think we should say to expect only the words with lexical data, maybe in 'Note: the Flashcard export is limited to a maximum of 25 words'?

>I agree the behavior is ok, but I'm not sure if it warrants a note on the download page -- do you think we could just make a note in the FAQ?

@monzug and @balmas , should I do here anything else?
try to reproduce some problem scenario?

**Comment by monzug** [comment]
if the loading problem is solved via #389, there is only one thing left: shall we add a note in the FAQ or somewhere else that failed lexical query are not  downloaded?

**Comment by balmas** [comment]
> if the loading problem is solved via #389, there is only one thing left: shall we add a note in the FAQ or somewhere else that failed lexical query are not downloaded?

Yes I think we should add that to the FAQ. I'm adding the faq label to this issue and am going to start working on the documentation for the release soon.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200602407
Alpheios Components 3.3.0-qa.20200602383

**Comment by monzug** [comment]
uhm, the loading for ever is still reproducible. also by clicking on the saved loading from wordlist it does load for ever
![loading-again](https://user-images.githubusercontent.com/41396793/83653421-c4dad600-a589-11ea-80f9-4678df4909a5.JPG)

is this going to be fixed by #389? I don't see the status being updated on #389

**Comment by balmas** [comment]
Hmm. This should have been fixed in this build.

**Comment by monzug** [comment]
in Chrome on Mac, instead of getting Loading, it doesn't do anything. I do not get the morphological pop-up but the word is added to wordlist and it does display correctly. double clicking on it from wordlist it does load the morphology pop-up
![Screen Shot 2020-06-03 at 5 29 53 PM](https://user-images.githubusercontent.com/41396793/83657020-94625e80-a5c0-11ea-9797-476566870db5.png)
![Screen Shot 2020-06-03 at 3 16 26 PM](https://user-images.githubusercontent.com/41396793/83657029-97f5e580-a5c0-11ea-93e1-936df003bbb0.png)

**Comment by monzug** [comment]
this is Chrome on PC
![Chrome-PC-loading](https://user-images.githubusercontent.com/41396793/83657186-84318b80-a58e-11ea-9025-fcc502253ca7.JPG)

**Comment by monzug** [comment]
so the loading issue is reported in #348 
this one should be only related to issue 2)

**Comment by monzug** [comment]
tested in Chrome on PC. Confirm that double clicking from wordlist for words with no lexical data works fine. Only Pindarus return a blank pop-up several times.

![pindarus-from-wordlist](https://user-images.githubusercontent.com/41396793/83753408-3c673e80-a638-11ea-808c-5dedb0fbe3f9.JPG)

![pindarus](https://user-images.githubusercontent.com/41396793/83753409-3cffd500-a638-11ea-94e2-ad68259a6365.JPG)

**Comment by balmas** [comment]
That's an interesting difference in behavior. I believe it occurs because Pindarus has no results from the morphological parser and no short definition, but it does have a full definition because it's found in the lexicon. So I think it ends up getting cached with a Homonym object that doesn't have a short definition. This is an edge case so I'm okay with it, but I will open an issue because it's worth looking at later.

**Comment by monzug** [comment]
well, I found several words behaving like Pindarus. Obviously, I didn't
make a list of them...

**Comment by balmas** [comment]
That's now issue #418

**Comment by balmas** [comment]
can we verify this one @monzug ?
