### ISSUE TITLE
Alpheios logo looks small in Big Sur

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#559]
The Alpheios logo is pretty small. Bridget said that she was worried about this when she saw that they made changes to icons in Big Sur
![Screen Shot 2020-11-17 at 4 58 07 PM](https://user-images.githubusercontent.com/41396793/99428103-7dad8b00-2906-11eb-8b47-83045566ab34.png)

**Comment by balmas** [comment]
should be fixed in Alpheios Reading Tools 3.3.3 build qa.20210118388

**Comment by monzug** [comment]
The logo has changed in the dock to match the safari and chrome icons. see attachment
![Screen Shot 2021-01-18 at 3 34 51 PM](https://user-images.githubusercontent.com/41396793/104928831-65f49080-59a3-11eb-8143-707879b9699f.png)

I still do not see any size changes of the Alpheios icon in the Safari toolbar. 

![Screen Shot 2021-01-18 at 3 36 25 PM](https://user-images.githubusercontent.com/41396793/104929444-2d08eb80-59a4-11eb-9b28-418e6a700e88.png)



also I noticed that the Alpheios icon in the configuration pop-up has the tails of the river in an unusual position. see attachment

![Screen Shot 2021-01-18 at 3 35 22 PM](https://user-images.githubusercontent.com/41396793/104929430-27130a80-59a4-11eb-8f72-564e45131e89.png)

**Comment by balmas** [comment]
I noticed that weird thing with the icon in the help too and was going to fix it with the next build.

Does the icon in the toolbar not look any different at all? I thought it looked a little better in Mac 10 Catalina. I haven't upgraded to Big Sur yet.  Can you send me a screenshot of that?

![Screen Shot 2021-01-18 at 11 11 51 AM](https://user-images.githubusercontent.com/644870/104939238-2bc4c800-597e-11eb-89d7-e8ac62bdedcd.png)

**Comment by monzug** [comment]
![Screen Shot 2021-01-18 at 5 21 14 PM](https://user-images.githubusercontent.com/41396793/104940188-ad821900-59b1-11eb-83dc-c9b91218b444.png)

and there is one above with alpheios no active (still blue though)

**Comment by monzug** [comment]
this is in Chrome on Mac
![Screen Shot 2021-01-18 at 5 24 18 PM](https://user-images.githubusercontent.com/41396793/104940452-09e53880-59b2-11eb-84fb-a4f9ca9f55aa.png)

**Comment by balmas** [comment]
Ugh, so Safari adds that awful blue color automatically to the extension when it's active. They say if we give them a colored icon they will use that color instead, but I think maybe we can have only 1 color and our colored version of the icon has 2 (blue and black) and I'm having trouble getting one that works. I'm not sure, if I can get a colored one to work if it will look good only older versions of the browser though, because previously the requirement from Apple was to NOT have a colored icon.  I'll try a few more things, not sure I'm going to get this resolved satisfactorily right now.

**Comment by balmas** [comment]
the icon on the help page should be fixed in webextension build qa.20210119566

fixing the icon on the toolbar is going to have to wait.  We can only have 1 color, and that won't work well for the older browsers which won't handle the grayscaling appropriately.

**Comment by monzug** [comment]
Thanks for fixing the icon on the help page. see attachment

![Screen Shot 2021-01-20 at 2 19 43 PM](https://user-images.githubusercontent.com/41396793/105180400-d0840880-5b2a-11eb-9253-6f42b7e55853.png)

**Comment by monzug** [comment]
@balmas, I marked this one as verified. not sure if we want to keep track of the icon on toolbar with this item, a new one or let it go. advise, pls.

**Comment by balmas** [comment]
I'll make a new issue. Thank you!
