### ISSUE TITLE
Multiple popups opened simultaneously

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alpheios-core#663]
I also got multiple popups opened simultaneously (occasionally) in the Latin pages.
![Screen Shot 2021-11-17 at 1 55 18 PM](https://user-images.githubusercontent.com/41396793/142204865-b07517d0-aed1-4786-9529-3871adb22bbf.png)

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/622#issuecomment-971543748_

**Comment by irina060981** [comment]
I believe that it was caused bu another bug in webextension.
Now it should be fixed in new Release
https://github.com/alpheios-project/webextension/releases

**Comment by monzug** [comment]
tested in FF/PC in build  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211118345
Alpheios Components 3.3.3-incr-3.4.x.20211116233 build i662-lexical-dicts.20211118457 

I haven't seen the 3 pop-ups opened simultaneously but I still see more than one pop-up, when page language is Greek and the morphology pop-up is in Latin. see below
![diffidere](https://user-images.githubusercontent.com/41396793/142430455-f3f061b3-d4a5-480d-aa1d-d774b70e2ddb.JPG)

**Comment by irina060981** [comment]
Will try to reproduce

**Comment by irina060981** [comment]
I am sorry, Monica, but I could not reproduce it in a new build (I saw it before my last changes).

So - if you still could reproduce it (from the latest build - be sure, that you clear previous build), I need detailed steps.

Previously these bug was because extension was attached several times (on page reload, on moving tab, on rechoosing tab).
That's why several popups was rendered at a time.

But now I could not reproduce several attachments, that's why I don't see any possibility to have more than one popup.
Waiting for steps from you.

**Comment by monzug** [comment]
I reinstall FF and latest alpheios build. I do not see any double pop-ups anymore. great
